# Generated by Django 3.0.2 on 2020-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsForSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('image1', models.ImageField(upload_to='C:/Users/Dereje/PyProjects/eSHEMBU/product/Images')),
                ('image2', models.ImageField(upload_to='C:/Users/Dereje/PyProjects/eSHEMBU/product/Images')),
                ('image3', models.ImageField(upload_to='C:/Users/Dereje/PyProjects/eSHEMBU/product/Images')),
                ('image4', models.ImageField(upload_to='C:/Users/Dereje/PyProjects/eSHEMBU/product/Images')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('amountInStock', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('packageWeight', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
