# Generated by Django 3.0.2 on 2020-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsforsell',
            name='image1',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='productsforsell',
            name='image2',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='productsforsell',
            name='image3',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='productsforsell',
            name='image4',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
        migrations.AlterField(
            model_name='productsforsell',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
    ]
