# Generated by Django 3.0.2 on 2020-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='userName',
            field=models.CharField(default='dereje', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
